GithubJS/GitJS/urls.py
from django.urls import path

from . import views, project_views, branch_views, milestone_views, file_views, \
    other_views, issue_views, pull_request_views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:project_id>/", project_views.single_project, name="single_project"),
    path("add_project", project_views.add_project, name="add_project"),
    path("delete_project/<int:project_id>", project_views.delete_project, name="delete_project"),
    path("branch/<int:branch_id>", file_views.single_branch, name="single_branch"),
    path("<int:project_id>/add_branch/", branch_views.add_branch, name="add_branch"),
    path("delete_branch/<int:branch_id>", branch_views.delete_branch, name="delete_branch"),
    path("edit_branch/<int:branch_id>", branch_views.edit_branch, name="edit_branch"),
    path('set_default/<int:branch_id>', branch_views.set_default, name="set_default"),
    path('copy_branch/<int:branch_id>', branch_views.copy_branch, name="copy_branch"),
    path("testredis/", views.cached_initial, name="test_redis_page"),
    path('login/', views.git_login, name='git_login'),
    path('logout/', views.git_logout, name='git_logout'),
    path('register/', views.git_register, name='git_register'),
    path('edit_profile/<int:user_id>', views.edit_profile, name='edit_profile'),
    path('delete_profile/<int:user_id>', views.delete_profile, name='delete_profile'),
    path('add_starred/<int:project_id>', project_views.add_starred, name='add_starred'),
    path('remove_starred/<int:project_id>', project_views.remove_starred, name='remove_starred'),
    path('my_starred/', project_views.starred_projects, name='my_starred'),
    path('start_watch/<int:project_id>', project_views.add_watched, name='add_watched'),
    path('stop_watch/<int:project_id>', project_views.remove_watched, name='remove_watched'),
    path('my_watched/', project_views.watched_project_changes, name='my_watched'),
    path('fork/<int:project_id>', project_views.fork_project, name='fork'),
    path('my_projects', project_views.my_projects, name='my_projects'),
    path('milestones/<int:project_id>/<str:state>', milestone_views.get_milestones, name='milestones'),
    path('<int:project_id>/add_milestone', milestone_views.add_milestone, name='add_milestone'),
    path('edit_milestone/<int:milestone_id>', milestone_views.edit_milestone, name='edit_milestone'),
    path('toggle_milestone/<int:milestone_id>', milestone_views.toggle_milestone_status, name='toggle_milestone'),
    path('<int:branch_id>/add_file', file_views.add_file, name='add_file'),
    path('edit_file/<int:file_id>', file_views.edit_file, name='edit_file'),
    path('delete_file/<int:file_id>', file_views.delete_file, name='delete_file'),
    path('contributors/<int:project_id>', project_views.contributors, name='contributors'),
    path('add_contributor/<int:project_id>', project_views.add_contributor, name='add_contributor'),
    path('remove_contributor/<int:project_id>/<str:username>', project_views.remove_contributor,
         name='remove_contributor'),
    path('add_comment/<int:project_id>', other_views.add_comment, name='add_comment'),
    path('toggle_reaction/<int:comment_id>/<str:reaction_type>', other_views.toggle_reaction,
         name='toggle_reaction'),
    path('issues/<int:project_id>/<str:state>', issue_views.get_issues, name='issues'),
    path('<int:project_id>/add_issue', issue_views.add_issue, name='add_issue'),
    path('edit_issue/<int:issue_id>', issue_views.edit_issue, name='edit_issue'),
    path('toggle_issue/<int:issue_id>', issue_views.toggle_issue_status, name='toggle_issue'),
    path('milestone_issues/<int:milestone_id>/<str:state>', issue_views.get_milestone_issues, name='milestone_issues'),
    path('commits/<int:branch_id>', branch_views.get_commit_history, name='commits'),
    path('pull_requests/<int:project_id>/<str:state>', pull_request_views.view_pull_requests, name='pull_requests'),
    path('<int:project_id>/add_pull_request', pull_request_views.add_pull_request, name='add_pull_request'),
    path('edit_pull_request/<int:pr_id>', pull_request_views.edit_pull_request, name='edit_pull_request'),
    path('toggle_request_state/<int:pr_id>', pull_request_views.toggle_request_state, name='toggle_request_state'),
    path('get_merge_changes/<int:pr_id>', pull_request_views.get_merge_changes, name='get_merge_changes'),
    path('merge_request/<int:pr_id>', pull_request_views.merge_request, name='merge_request'),
    path('search_app', other_views.search_app, name='search_app')
]

GithubJS/GithubJS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("GitJS.urls")),
    path("admin/", admin.site.urls),
]

GithubJS/GitJS/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class GitUser(User):

    def get_my_projects(self):
        all_projects = Project.objects.all()
        my_projects = []
        for project in all_projects:
            if project.can_edit(self.username):
                my_projects.append(project)
        return my_projects

    def get_starred_projects(self):
        starred_projects = StarredProject.objects.filter(user_id=self.pk)
        starred = []
        for sp in starred_projects:
            starred.append(Project.objects.get(id=sp.project_id))
        return starred

    def add_starred(self, project_id):
        new_starred = StarredProject(project_id=project_id, user_id=self.pk)
        new_starred.save()

    def remove_starred(self, project_id):
        starred = StarredProject.objects.get(project_id=project_id, user_id=self.pk)
        starred.delete()

    def get_watched_changes(self):
        watched_projects = ProjectUpdate.objects.filter(user_id=self.pk).order_by('-up_date')
        return watched_projects

    def add_watched(self, project_id):
        new_watched = WatchedProject(project_id=project_id, user_id=self.pk)
        new_watched.save()

    def remove_watched(self, project_id):
        watched = WatchedProject.objects.get(project_id=project_id, user_id=self.pk)
        watched.delete()


class Project(models.Model):
    title = models.CharField(max_length=100)
    forked_from = models.ForeignKey('self', null=True, on_delete=models.SET_NULL)
    lead = models.ForeignKey(GitUser, on_delete=models.CASCADE)

    def get_branch_number(self):
        branches = Branch.objects.filter(project=self)
        return len(branches)

    def get_branches(self):
        branches = Branch.objects.filter(project=self)
        return branches

    def update_users(self, message):
        for watched in WatchedProject.objects.filter(project_id=self.id):
            new_date = timezone.now()
            update = ProjectUpdate(project_id=self.id, user_id=watched.user_id, up_date=new_date, message=message)
            update.save()

    def get_milestones(self, state):
        milestones = Milestone.objects.filter(project=self, state=state)
        return milestones

    def get_issues(self, state):
        issues = Issue.objects.filter(project=self, state=state)
        return issues

    def get_pull_requests(self, state):
        pull_requests = []
        if state == 'OPEN':
            pull_requests = PullRequest.objects.filter(project=self, state=state)
        else:
            all_requests = PullRequest.objects.filter(project=self)
            for req in all_requests:
                if req.state == 'CLOSED' or req.state == 'MERGED':
                    pull_requests.append(req)
        return pull_requests

    def get_contributors(self):
        contributors = Contributor.objects.filter(project_id=self.id)
        return contributors

    def get_noncontributors(self):
        ret = []
        for con in GitUser.objects.all():
            if self.lead.username != con.username and \
             len(Contributor.objects.filter(username=con.username, project_id=self.id)) == 0:
                ret.append(con.username)
        return ret

    def get_all_participants(self):
        participants = []
        for contributor in self.get_contributors():
            participants.append(contributor.username)
        participants.append(self.lead.username)
        return participants

    def can_edit(self, username):
        for participant in self.get_all_participants():
            if participant == username:
                return True
        return False

    def get_comments(self, username):
        comments = Comment.objects.filter(project=self).order_by('-last_update')
        ret = []
        for comment in comments:
            user = GitUser.objects.get_by_natural_key(username)
            reaction = Reaction.objects.filter(comment=comment, user=user)
            if len(reaction) == 0:
                ret.append({"comment": comment, "reaction": ""})
            else:
                ret.append({"comment": comment, "reaction": reaction[0].type})
        return ret


class StarredProject(models.Model):
    project_id = models.BigIntegerField()
    user_id = models.BigIntegerField()


class WatchedProject(models.Model):
    project_id = models.BigIntegerField()
    user_id = models.BigIntegerField()


class Contributor(models.Model):
    project_id = models.BigIntegerField()
    username = models.CharField(max_length=100)


class ProjectUpdate(models.Model):
    up_date = models.DateTimeField("date updated")
    message = models.CharField(max_length=100)
    project_id = models.BigIntegerField()
    user_id = models.BigIntegerField()


class Branch(models.Model):
    name = models.CharField(max_length=100)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    default = models.BooleanField()

    def get_commits(self):
        commits = Commit.objects.filter(branch=self).order_by('-date_time')
        return commits

    def get_files(self):
        files = File.objects.filter(branch=self)
        return files

    def get_file_by_title(self, title):
        found = File.objects.filter(branch=self, title=title)
        if len(found) == 0:
            return None
        return found[0]


class Milestone(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    due_date = models.DateTimeField("due date")
    state = models.CharField(max_length=7)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def get_issues(self, state):
        issues = Issue.objects.filter(milestone=self, state=state)
        return issues

    def get_percent(self):
        completed = len(Issue.objects.filter(milestone=self, state='CLOSED'))
        total = len(Issue.objects.filter(milestone=self))
        return int(round((completed * 100) / total, 2)) if total != 0 else 0


class File(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=200)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)


class Comment(models.Model):
    text = models.CharField(max_length=200)
    last_update = models.DateTimeField("last update")
    user = models.ForeignKey(GitUser, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Reaction(models.Model):
    type = models.CharField(max_length=10)
    user = models.ForeignKey(GitUser, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


class Issue(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    state = models.CharField(max_length=7)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    milestone = models.ForeignKey(Milestone, null=True, on_delete=models.SET_NULL)
    assignee = models.ForeignKey(GitUser, null=True, on_delete=models.SET_NULL)


class Commit(models.Model):
    log_message = models.CharField(max_length=200)
    date_time = models.DateTimeField("date committed")
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    committer = models.CharField(max_length=100)


class PullRequest(models.Model):
    state = models.CharField(max_length=7)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    issue = models.ForeignKey(Issue, null=True, on_delete=models.SET_NULL)
    source = models.ForeignKey(Branch, null=True, on_delete=models.SET_NULL, related_name='source')
    target = models.ForeignKey(Branch, null=True, on_delete=models.SET_NULL, related_name='target')

    def get_differences(self):
        different_files = self.source.get_files()
        differences = []
        for different in different_files:
            if self.target.get_file_by_title(different.title):
                target_file = self.target.get_file_by_title(different.title)
                differences.append([target_file.text, different.text])
            else:
                differences.append(['', different.text])
        return differences

    def merge_branches(self):
        source_files = self.source.get_files()
        new_files = []
        new_id = File.objects.all().order_by('-id')[0].id + 1
        for file in source_files:
            if self.target.get_file_by_title(file.title):
                changed = File.objects.get(title=file.title, branch=self.target)
                changed.text = file.text
                changed.save()
            else:
                new_file = File(id=new_id, title=file.title, text=file.text, branch=self.target)
                new_files.append(new_file)
                new_id += 1
        File.objects.bulk_create(new_files)

GithubJS/GitJS/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <title>{{title}}</title>
</head>
<body>
<div class="page">
  <div class="header">
    <h1>GITHUB JS HOME</h1>
  </div>
    <div class="left">
      <ul class="list-group">
          <li class="list-group-item">
              <a href="{% url 'index' %}">Home</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="list-group-item">
            <a href="{% url 'search_app' %}">
                Search application
            </a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'git_logout' %}">Log Out</a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'edit_profile' request.user.id %}">Edit profile</a>
          </li>
          <li class="list-group-item">
            <a></a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'delete_profile' request.user.id %}">Delete profile</a>
          </li>
          <li class="list-group-item">
            <a></a>
          </li>
          <li class="list-group-item">
              <a href="{% url 'my_projects' %}">My projects</a>
          </li>
          <li class="list-group-item">
              <a href="{% url 'my_watched' %}">Watched project changes</a>
          </li>
          <li class="list-group-item">
              <a href="{% url 'my_starred' %}">Starred projects</a>
          </li>
          {% else %}
          <li class="list-group-item">
            <a href="{% url 'git_login' %}">Log In</a>
          </li>
          {% endif %}
          <li class="list-group-item">
              <a href="{% url 'test_redis_page' %}">Redis test</a>
          </li>
      </ul>
      {% block links %}{% endblock %}
    </div>
    <div class="center">
      {% block content %}{% endblock %}
    </div>
    <div class="footer">This is a clone of Github created by Jovan Svorcan R2 21/2021</div>
</div>
</body>
</html>

GithubJS/GitJS/templates/branch_form.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'single_project' project.id %}">
        <button class="btn btn-primary">Back</button>
    </a>
    <br><br>
    <h2>{{project.title}} - {{title}}</h2>
    <br>
    <form action="/{{form_action}}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="new_branch">Branch name</label><br>
        <input type="text" name="new_branch" id="new_branch" value="{{input_value}}">
    </fieldset>
        <br>
    {% if input_value == '' %}
        <input type="submit" value="Add" class="btn btn-success">
    {% else %}
        <input type="submit" value="Change" class="btn btn-warning">
    {% endif %}
    </form>
{% endblock %}

GithubJS/GitJS/templates/commits.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'single_branch' branch.id %}">
        <button class="btn btn-primary">Back</button>
    </a>
    <br><br>

    <h3>All commits for {{branch.name}}</h3>

    <br>

    {% for commit in commits %}
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5>{{commit.log_message}}</h5>
              <small>{{commit.date_time}}</small>
            </div>
            <p class="mb-1">by {{commit.committer}}</p>
        </a>
    </div>
    {% endfor %}

{% endblock %}

GithubJS/GitJS/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to JSTheGreat's Github clone</h1>
{% endblock %}

GithubJS/GitJS/templates/issue_form.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'issues' project_id 'OPEN' %}">
        <button class="btn btn-primary">Back</button>
    </a>
    <br><br>
    <h2>{{ title }}</h2>

    <br>
    <form action="/{{form_action}}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="new_title">Title</label><br>
        <input type="text" name="new_title" id="new_title" value="{{input_title}}" class="form-control" required
            {% if not can_edit %} disabled {% endif %}>

        <label for="new_desc">Description</label><br>
        <textarea class="form-control" type="text" name="new_desc" id="new_desc"
                  rows="3" {% if not can_edit %} disabled {% endif %}>{{input_desc}}</textarea>

        <label for="assignee">Assignee</label><br>
        <select class="form-control" id="assignee" name="assignee"
            {% if not can_edit %} disabled {% endif %}>
            <option>None</option>
            {% for participant in participants %}
                {% if participant == input_assignee %}
                <option selected>{{participant}}</option>
                {% else %}
                <option>{{participant}}</option>
                {% endif %}
            {% endfor %}
        </select>

        <label for="milestone">Milestone</label><br>
        <select class="form-control" id="milestone" name="milestone"
            {% if not can_edit %} disabled {% endif %}>
            <option>None</option>
            {% for milestone in milestones %}
                {% if milestone.title == input_milestone %}
                <option selected>{{milestone.title}}</option>
                {% else %}
                <option>{{milestone.title}}</option>
                {% endif %}
            {% endfor %}
        </select>
    </fieldset>

    {% if can_edit %}
            <br>
        {% if input_title == '' %}
            <input type="submit" value="Add" class="btn btn-success">
        {% else %}
            <input type="submit" value="Change" class="btn btn-warning">
        {% endif %}
    {% endif %}
    </form>
{% endblock %}

GithubJS/GitJS/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style-login.css' %}"/>
    <title>{{ title }}</title>

</head>
<body>

<a href="{% url 'index' %}">
    <button class="btn btn-primary">Main page</button>
</a>
<br><br>

<h2>Login Form</h2>

<form action="{% url 'git_login' %}" method="post">
    {% csrf_token %}

    <div class="container">
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter username..." id="uname" name="uname" required>

        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter password..." id="psw" name="psw" required>

        <a href="{% url 'git_register' %}">
            Don't have an account yet? Register here
        </a>

        <button type="submit">Log In</button>
        {% if login_has_error %}
        <label>
            <span class="err">Wrong username or password</span>
        </label>
        {% endif %}
    </div>

</form>

</body>
</html>

GithubJS/GitJS/templates/merge_changes.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'pull_requests' project_id 'OPEN' %}">
        <button class="btn btn-primary">Back</button>
    </a>
    <br><br>

    <h1>{{ title }}</h1>
    <br><br>

    <div class="fluid-container">

        <div class="row mt-4">
            <div class="col-md-6 d-flex justify-content-center">
                <b>Before</b>
            </div>
            <div class="col-md-6 d-flex justify-content-center">
                <b>After</b>
            </div>
        </div>

        {% for before, after in changes %}
        <div class="row mt-5">
            {% if before == '' %}
            <textarea class="col-md-6 bg-success text-white" disabled>
                {{before}}
            </textarea>
            <textarea class="col-md-6 bg-success text-white" disabled>
                {{after}}
            </textarea>
            {% else %}
            <textarea class="col-md-6 bg-warning text-white" disabled>
                {{before}}
            </textarea>
            <textarea class="col-md-6 bg-warning text-white" disabled>
                {{after}}
            </textarea>
            {% endif %}
        </div>
    {% endfor %}

    </div>

    <br><br>
    <a href="{% url 'merge_request' pr_id %}">
        <button class="btn btn-primary">Merge</button>
    </a>
{% endblock %}

GithubJS/GitJS/templates/milestone_form.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'single_project' project_id %}">
        <button class="btn btn-primary">Back</button>
    </a>
    <br><br>

    <h2>{{ title }}</h2>

    {% if input_title != '' %}
        <br>
        <h6>{{percent}} % complete</h6>
    {% endif %}

    <br>
    <form action="/{{form_action}}" method="post">
    {% csrf_token %}
    <fieldset>
        {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="new_title">Title</label><br>
        <input type="text" name="new_title" id="new_title" value="{{input_title}}" class="form-control" required
            {% if not can_edit %} disabled {% endif %}>

        <label for="new_desc">Description</label><br>
        <textarea class="form-control" type="text" name="new_desc" id="new_desc"
                  rows="3" required {% if not can_edit %} disabled {% endif %}>{{input_desc}}</textarea>

        <label for="due_date">Due date</label><br>
        <input type="date" name="due_date" id="due_date" value="{{due_date}}" class="form-control" required
            {% if not can_edit %} disabled {% endif %}>
    </fieldset>

    {% if can_edit %}
        <br>
        {% if input_title == '' %}
            <input type="submit" value="Add" class="btn btn-success">
        {% else %}
            <input type="submit" value="Change" class="btn btn-warning">
        {% endif %}
    {% endif %}
    </form>
{% endblock %}

GithubJS/GitJS/templates/project_view.html
{% extends "base.html" %}
{% block content %}
    {% if not can_fork %}
    <a href="{% url 'delete_project' project.id %}">
        <button class="btn btn-danger">DELETE PROJECT</button>
    </a>
    <br><br>
    {% endif %}

    <h1>{{ project.title }}</h1>

    {% if project.forked_from %}
    <br>
    <p>Forked from:
        <a href="{% url 'single_project' project.forked_from.id %}">
            {{project.forked_from.lead.username}}/{{project.forked_from.title}}
        </a>
    </p>
    {% endif %}

    <div>
        {% if starred %}
        <a href="{% url 'remove_starred' project.id %}">
            <button class="btn btn-info">Unstar</button>
        </a>
        {% else %}
        <a href="{% url 'add_starred' project.id %}">
            <button class="btn btn-info">Star</button>
        </a>
        {% endif %}

        {% if watched %}
        <a href="{% url 'remove_watched' project.id %}">
            <button class="btn btn-info">Unwatch</button>
        </a>
        {% else %}
        <a href="{% url 'add_watched' project.id %}">
            <button class="btn btn-info">Watch</button>
        </a>
        {% endif %}

        {% if can_fork %}
        <a href="{% url 'fork' project.id %}">
            <button class="btn btn-info">Fork</button>
        </a>
        {% endif %}

        <a class="ms-5" href="{% url 'issues' project.id 'OPEN' %}">
            <button class="btn btn-secondary">Issues</button>
        </a>

        <a href="{% url 'milestones' project.id 'OPEN' %}">
            <button class="btn btn-secondary">Milestones</button>
        </a>

        <a href="{% url 'pull_requests' project.id 'OPEN' %}">
            <button class="btn btn-secondary">Pull requests</button>
        </a>

        {% if project.lead.username == user.username %}
        <a class="ms-5" href="{% url 'contributors' project.id %}">
            <button class="btn btn-info">Contributors</button>
        </a>
        {% endif %}
    </div>
    <br>
    <ul class="list-group">
    {% for branch in project.branch_set.all %}
        <li class="list-group-item">
            {% if branch.default %}
                <a href="{% url 'single_branch' branch.id %}">
                    {{ branch.name }} (default)
                </a>
            {% else %}
                <a href="{% url 'single_branch' branch.id %}">{{ branch.name }}</a>
            {% endif %}
            {% if can_edit %}
                <a href="{% url 'copy_branch' branch.id %}">
                    <button class="btn btn-primary">Copy</button>
                </a>
                <a href="{% url 'edit_branch' branch.id %}">
                    <button class="btn btn-warning">Edit</button>
                </a>
                <a href="{% url 'delete_branch' branch.id %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>

    {% if can_edit %}
        <br>
        <a href="{% url 'add_branch' project.id %}">
            <button class="btn btn-success">Add branch</button>
        </a>
    {% endif %}

    <br><br>
    <form action="{% url 'add_comment' project.id %}" method="post">
    {% csrf_token %}
    {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="new_comment">
        <input type="text" class="form-control" name="new_comment" id="new_comment" required>
        <button type="submit" class="btn btn-primary">Add comment</button>
    </div>
    </form>
    {% for comment in comments %}
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">{{comment.comment.user.username}}</h5>
              <small>{{comment.comment.last_update}}</small>
            </div>
            <p class="mb-1">{{comment.comment.text}}</p>
            <small>
                {% if comment.reaction == 'LIKE' %}
                    <a href="{% url 'toggle_reaction' comment.comment.id 'LIKE' %}" class="LIKE">LIKED</a>
                {% else %}
                    <a href="{% url 'toggle_reaction' comment.comment.id 'LIKE' %}">LIKE</a>
                {% endif %}
                <span>    </span>
                {% if comment.reaction == 'DISLIKE' %}
                    <a href="{% url 'toggle_reaction' comment.comment.id 'DISLIKE' %}" class="DISLIKE">DISLIKED</a>
                {% else %}
                    <a href="{% url 'toggle_reaction' comment.comment.id 'DISLIKE' %}">DISLIKE</a>
                {% endif %}
            </small>
        </a>
    </div>
    {% endfor %}

{% endblock %}

GithubJS/GitJS/templates/projects.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ title }}</h1>

    <br>
    <ul class="list-group">
    {% for project in projects %}
        <li class="list-group-item">
            <a href="{% url 'single_project' project.id %}">
                {{project.lead.username}} - {{ project.title }}
            </a>
        </li>
    {% endfor %}
    </ul>

    <br><br>
    {% if can_add %}
    <a href="{% url 'add_project' %}">
        <button class="btn btn-success">
            New project
        </button>
    </a>
    {% endif %}

{% endblock %}

GithubJS/GitJS/templates/updates.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ title }}</h1>
    <br>

    <ul class="list-group">
    {% for change in changes %}
    <li class="list-group-item">
        <a href="{% url 'single_project' change.project_id %}">
            {{change.project_id}}
        </a>
        <span>{{change.message}} on {{change.up_date}}</span>
    </li>
    {% endfor %}
    </ul>
{% endblock %}